name: wrd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  animated_text_kit: ^4.2.2
  assets_audio_player: ^3.1.0
  audio_service: ^0.18.12
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^5.1.0
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_carousel_slider: ^1.1.0
  flutter_local_notifications: ^15.1.1
  flutter_localization: ^0.1.13
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_qiblah: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  hijri: ^3.0.0
  http: ^0.13.5
  hydrated_bloc: ^9.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.10
  lottie: ^2.3.2
  permission_handler: ^11.0.0
  shared_preferences: ^2.1.0
  timezone: ^0.9.2
  url_launcher: ^6.1.13
  flutter_onboarding_slider: ^1.0.11
  smooth_page_indicator: ^1.1.0
  vibration: ^1.8.4

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/
    - assets/jsons_file/
    - assets/json/
    - assets/database/
    - assets/notification/Landscape.png
    - assets/onbording/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Font_0.ttf
        - asset: assets/fonts/Almarai-Font.ttf
        - asset: assets/fonts/Almarai-Light.ttf

    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs.ttf

    - family: ae_Granada
      fonts:
        - asset: assets/fonts/ae_Granada.ttf

    - family: Aldhabi
      fonts:
        - asset: assets/fonts/Aldhabi.ttf

flutter_intl:
  enabled: true
